// Code generated by swagger-doc. DO NOT EDIT.

package v1alpha1

func (StorageMigration) SwaggerDoc() map[string]string {
	return map[string]string{
		"":       "StorageMigration defines the operation of moving the storage to another\nstorage backend.\n+genclient\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
		"status": "+optional",
	}
}

func (StorageMigrationList) SwaggerDoc() map[string]string {
	return map[string]string{
		"":      "StorageMigrationList is a list of StorageMigration resources\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
		"items": "+listType=atomic",
	}
}

func (MigratedVolume) SwaggerDoc() map[string]string {
	return map[string]string{
		"sourcePvc":              "VMIName        string `json:\"vmiName,omitempty\" valid:\"required\"`",
		"reclaimPolicySourcePvc": "ReclaimPolicySourcePvc describes how the source volumes will be\ntreated after a successful migration\n+optional",
	}
}

func (StorageMigrationSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"":               "StorageMigrationSpec is the spec for a StorageMigration resource",
		"migratedVolume": "MigratedVolumes is a list of volumes to be migrated\n+optional",
	}
}

func (StorageMigrationState) SwaggerDoc() map[string]string {
	return map[string]string{
		"":                            "StorageMigrationState is the status for a StorageMigration resource",
		"migratedVolume":              "MigratedVolumes is a list of volumes to be migrated\n+optional",
		"virtualMachineMigrationName": "VirtualMachineMigrationState state of the virtual machine migration\ntriggered by the storage migration\n+optional",
		"completed":                   "+optional",
		"failed":                      "+optional",
	}
}

func (StorageMigrationStatus) SwaggerDoc() map[string]string {
	return map[string]string{}
}
